import dayjs from 'dayjs/esm';

import { IFtOResv, NewFtOResv } from './ft-o-resv.model';

export const sampleWithRequiredData: IFtOResv = {
  id: 3669,
};

export const sampleWithPartialData: IFtOResv = {
  id: 4069,
  numLigne: 11179,
  resvNameId: 3149,
  businessDate: dayjs('2023-10-24'),
  clientMdmId: 'broadly',
  nameId: 20434,
  contactId: 20566,
  societeId: 17521,
  groupeId: 95,
  statutResv: 'animated',
  dateDebutLigne: dayjs('2023-10-24'),
  dateFinOrigine: dayjs('2023-10-23'),
  pseudoRoomYn: 'kiddingly flowery',
  complementaireYn: 'whether jubilantly woot',
  walkinYn: 'ah despite',
  codePays: 'generally with',
  codeSource: 'since',
  libSource: 'scarily',
  codeGrandSource: 'abaft',
  libMarche: 'methane',
  codeGrandMarche: 'yet',
  categPrix: 'slaw',
  descriptionTypeChb: 'whoa disambiguate infatuated',
  nbResvAnn: 22987,
  nbNuitee: 11103,
  nbNuiteeNnDed: 10565,
  nbNuiteeGlobal: 29385,
  nbOccupationMultiple: 5803,
  nbPersDayUGlobal: 1805,
  nbPersArrGlobal: 10119,
  nbPersAnn: 28135,
  nbPersNoshow: 22358,
  nbChbDayUGlobal: 5272,
  nbChbDepGlobal: 11209,
  nbChbNoshow: 1331,
  revenuNetBqGlobal: 8342,
  revenuNetExtraGlobal: 20428,
  revenuTaxeExtraGlobal: 583,
  revenuNetTotalGlobal: 28107,
  prodRevenuExtra: 31745,
  prodRevenuTotal: 12502,
  prodChambreNbNuitees: 29052,
  datesSejourRensYn: 'trouser briefly',
  techOrigine: 'yum',
  techGrpNumOrdre: 5047,
  techCreateDate: dayjs('2023-10-24'),
};

export const sampleWithFullData: IFtOResv = {
  id: 10494,
  numLigne: 2001,
  resort: 'abaft attract',
  resvNameId: 8612,
  clientOId: 'reconfigure',
  typeChb: 'renovate purl',
  businessDate: dayjs('2023-10-24'),
  numOrdre: 1788,
  confirmationNo: 'whenever owlishly ack',
  clientMdmId: 'without reproachfully dragoon',
  nameId: 17489,
  nameIdLigne: 21335,
  contactId: 22602,
  agenceId: 10741,
  agenceNom: 'truthful consequently donkey',
  societeId: 27941,
  groupeId: 16876,
  membreId: 23938,
  sourceProfileId: 22896,
  numBloc: 10373,
  statutResv: 'rust throughout',
  statutVip: 'justly intervene',
  dateDebutLigne: dayjs('2023-10-23'),
  dateFinLigne: dayjs('2023-10-24'),
  dateFinOrigine: dayjs('2023-10-24'),
  dateAnn: dayjs('2023-10-24'),
  pseudoRoomYn: 'boohoo',
  complementaireYn: 'fairly mmm',
  interneYn: 'pfft weakness sans',
  walkinYn: 'playfully appall pish',
  createurResv: 29009,
  nomCreateurResv: 'an piano stint',
  codePays: 'how abaft cyclooxygenase',
  libPays: 'circa',
  codeNationalite: 'after',
  libNationalite: 'mark',
  codeSource: 'bristle network',
  libSource: 'trial',
  codeGrandSource: 'the bivvy jubilantly',
  codeOrigine: 'aha',
  libOrigine: 'longingly sympathetically',
  codeMarche: 'aha',
  libMarche: 'utilized blindly if',
  codeGrandMarche: 'omnivore beneath violet',
  libGrandMarche: 'geez metamorphose',
  codePrix: 'hastily gorgeous amongst',
  categPrix: 'aha representation gah',
  libPrix: 'terribly ugh',
  numChb: 'ugh knottily unbearably',
  typeChbLigne: 'down flag',
  descriptionTypeChb: 'pace since cheerfully',
  codeTypeChb: 'unfortunate',
  classChb: 'thoughtfully',
  statutChbResv: 'when',
  typeChbDeReservation: 'despite',
  descriptionTypeChbDeResv: 'provided tightly evil',
  codeTypeChbDeResv: 'mollycoddle repossess',
  circuitDistribution: 'until athwart eek',
  circuitDistribUserRegroup: 'prescind zealous geez',
  nbResvAnn: 32026,
  nbNuitee: 20957,
  nbNuiteeNnDed: 13159,
  nbNuiteeGlobal: 5724,
  nbOccupationMultiple: 21948,
  nbAduGlobal: 17325,
  nbEnfGlobal: 18500,
  nbPersDayUGlobal: 6404,
  nbPersArrGlobal: 27805,
  nbPersDepGlobal: 1553,
  nbPersAnn: 20491,
  nbPersNoshow: 3324,
  nbChbDayUGlobal: 2001,
  nbChbArrGlobal: 10169,
  nbChbDepGlobal: 8947,
  nbChbAnn: 9763,
  nbChbNoshow: 27653,
  revenuNetChambreGlobal: 3347,
  revenuTaxeChambreGlobal: 28084,
  revenuNetBqGlobal: 16265,
  revenuTaxeBqGlobal: 8323,
  revenuNetExtraGlobal: 31909,
  revenuTaxeExtraGlobal: 14432,
  revenuNetTotalGlobal: 30134,
  revenuTaxeTotalGlobal: 31026,
  prodRevenuChambre: 29945,
  prodRevenuBq: 12019,
  prodRevenuExtra: 10943,
  prodRevenuTotal: 27250,
  prodChambreNbNuitees: 18019,
  datesSejourRensYn: 'tart',
  techEventType: 'savior shroud dispute',
  techResvInvType: 'blah hmph generously',
  techOrigine: 'sure-footed dramatic fish',
  techGrpNumOrdre: 24270,
  techCreateDate: dayjs('2023-10-24'),
  techUpdateDate: dayjs('2023-10-24'),
  resvNameIdPrincipal: 22401,
};

export const sampleWithNewData: NewFtOResv = {
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
